name: Sync, Fork and Generate A List Of Repo

on:
  # schedule:
  #   - cron: '0 0 * * *'
  push:
    branches:
      - refactor

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run index.ts
        run: cd task && npm install && npm run start
        env:
          # GH_TOKEN: ${{ secrets.GH_CLI_TOKEN }}
          GH_TOKEN: ${{ github.token }}

