name: Sync, Fork and Generate Repo List

on:
  schedule:
    - cron: '0 0/3 * * *'
  push:
    branches:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  update-refined-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Update refined_list
        run: cd crates && ./refined_list.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }} 
          add-paths: crates/refined_list.txt
          commit-message: "[bot] Update refined_list.txt"
          author: zjp-bot <zjp[bot]@users.noreply.github.com>
          delete-branch: true
          branch: update-refined-list
          base: main
          title: '[bot] Update refined_list.txt'

  run:
    runs-on: ubuntu-latest
    needs: update-refined-list
    steps:
      - uses: actions/checkout@v4

      - name: Run index.ts
        env:
          FORCE_COLOR: 3
          TEST: false
          EXECUTE: true
        run: cd task && npm install && npm run start

      - name: Upload os-checker_config.json os-checker_config-full.json refined_list.txt
        env:
          tag: v0.4.0
          files: os-checker_config.json os-checker_config-full.json refined_list.txt
        run: |
          cp crates/refined_list.txt task
          cd task
          ls -alh
          # create the tag if not exists
          gh release create ${{ env.tag }} --generate-notes --latest -R kern-crates/.github || true 
          gh release upload ${{ env.tag }} --clobber -R kern-crates/.github ${{ env.files }}
          echo ${{ env.files }} "uploaded."
          rm refined_list.txt
